[build]
  base = "client"  # This is the directory containing your React app
  publish = "/build"  # The directory where your built React files will be placed

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
